version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgis/postgis:13-3.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=carpool
      - POSTGRES_PASSWORD=carpool
      - POSTGRES_DB=carpool_dev

volumes:
  postgres_data:
