# Generated by Django 3.2.6 on 2022-08-05 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=200)),
                ('make_year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('registration_number', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city', to='rides.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city', to='rides.city')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_seats', models.IntegerField()),
                ('booked_seats', models.IntegerField()),
                ('status', models.CharField(choices=[('COMPLETED', 'Complete'), ('DELETED', 'Deleted'), ('AVAILABLE', 'Available')], default='AVAILABLE', max_length=10)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('NONE', 'none')], default='NONE', max_length=10)),
                ('date', models.DateField()),
                ('pickup_location', jsonfield.fields.JSONField(blank=True, default={})),
                ('dropoff_location', jsonfield.fields.JSONField(blank=True, default={})),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.cars')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredRides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.CharField(max_length=500)),
                ('number_of_riders', models.IntegerField()),
                ('date', models.DateField()),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ride_id')},
            },
        ),
    ]
