# Generated by Django 3.2.6 on 2022-08-24 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.CharField(max_length=500)),
                ('number_of_riders', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registered Rides',
                'unique_together': {('user', 'ride_id')},
            },
        ),
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cities'},
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='RegisteredRides',
        ),
    ]
