# Generated by Django 3.2.6 on 2022-08-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20220824_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredride',
            name='dropoff',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registeredride',
            name='pickup',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registeredride',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('PENDING', 'Pending'), ('WITHDRAWAL', 'Withdrawal')], default='PENDING', max_length=12),
        ),
        migrations.AlterField(
            model_name='ride',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
