# Generated by Django 3.2.6 on 2022-09-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_auto_20220827_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
