# Generated by Django 3.2.6 on 2022-09-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_city_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='booked_seats',
            field=models.IntegerField(default=0),
        ),
    ]
