# Generated by Django 3.2.6 on 2023-04-01 11:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_auto_20220908_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pickup_location',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(max_length=100)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.ride')),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='dropoff_locations',
            field=models.ManyToManyField(related_name='dropoff_locations', to='rides.Location'),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_locations',
            field=models.ManyToManyField(related_name='pickup_locations', to='rides.Location'),
        ),
    ]
