# Generated by Django 3.2.6 on 2023-04-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_auto_20230416_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredride',
            name='date',
        ),
    ]
