# Generated by Django 3.2.6 on 2023-04-16 09:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0008_remove_registeredride_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredride',
            old_name='ride_id',
            new_name='ride',
        ),
        migrations.AlterUniqueTogether(
            name='registeredride',
            unique_together={('user', 'ride')},
        ),
    ]
